package dwarf

Dwarf_Attribute :: enum {
	Sibling                        = 0x01,
	Location                       = 0x02,
	Name                           = 0x03,
	Ordering                       = 0x09,
	Subscr_Data                    = 0x0a,
	Byte_Size                      = 0x0b,
	Bit_Offset                     = 0x0c,
	Bit_Size                       = 0x0d,
	Element_List                   = 0x0f,
	Stmt_List                      = 0x10,
	Low_Pc                         = 0x11,
	High_Pc                        = 0x12,
	Language                       = 0x13,
	Member                         = 0x14,
	Discr                          = 0x15,
	Discr_Value                    = 0x16,
	Visibility                     = 0x17,
	Import                         = 0x18,
	String_Length                  = 0x19,
	Common_Reference               = 0x1a,
	Comp_Dir                       = 0x1b,
	Const_Value                    = 0x1c,
	Containing_Type                = 0x1d,
	Default_Value                  = 0x1e,
	Inline                         = 0x20,
	Is_Optional                    = 0x21,
	Lower_Bound                    = 0x22,
	Producer                       = 0x25,
	Prototyped                     = 0x27,
	Return_Addr                    = 0x2a,
	Start_Scope                    = 0x2c,
	Bit_Stride                     = 0x2e,
	Upper_Bound                    = 0x2f,
	Abstract_Origin                = 0x31,
	Accessibility                  = 0x32,
	Address_Class                  = 0x33,
	Artificial                     = 0x34,
	Base_Types                     = 0x35,
	Calling_Convention             = 0x36,
	Count                          = 0x37,
	Data_Member_Location           = 0x38,
	Decl_Column                    = 0x39,
	Decl_File                      = 0x3a,
	Decl_Line                      = 0x3b,
	Declaration                    = 0x3c,
	Discr_List                     = 0x3d,
	Encoding                       = 0x3e,
	External                       = 0x3f,
	Frame_Base                     = 0x40,
	Friend                         = 0x41,
	Identifier_Case                = 0x42,
	Macro_Info                     = 0x43,
	Namelist_Items                 = 0x44,
	Priority                       = 0x45,
	Segment                        = 0x46,
	Specification                  = 0x47,
	Static_Link                    = 0x48,
	Type                           = 0x49,
	Use_Location                   = 0x4a,
	Variable_Parameter             = 0x4b,
	Virtuality                     = 0x4c,
	Vtable_Elem_Location           = 0x4d,

	// DWARF 3 values.
	Allocated                      = 0x4e,
	Associated                     = 0x4f,
	Data_Location                  = 0x50,
	Byte_Stride                    = 0x51,
	Entry_Pc                       = 0x52,
	Use_UTF8                       = 0x53,
	Extension                      = 0x54,
	Ranges                         = 0x55,
	Trampoline                     = 0x56,
	Call_Column                    = 0x57,
	Call_File                      = 0x58,
	Call_Line                      = 0x59,
	Description                    = 0x5a,
	Binary_Scale                   = 0x5b,
	Decimal_Scale                  = 0x5c,
	Small                          = 0x5d,
	Decimal_Sign                   = 0x5e,
	Digit_Count                    = 0x5f,
	Picture_String                 = 0x60,
	Mutable                        = 0x61,
	Threads_Scaled                 = 0x62,
	Explicit                       = 0x63,
	Object_Pointer                 = 0x64,
	Endianity                      = 0x65,
	Elemental                      = 0x66,
	Pure                           = 0x67,
	Recursive                      = 0x68,

	// DWARF 4.
	Signature                      = 0x69,
	Main_Subprogram                = 0x6a,
	Data_Bit_Offset                = 0x6b,
	Const_Expr                     = 0x6c,
	Enum_Class                     = 0x6d,
	Linkage_Name                   = 0x6e,

	// DWARF 5
	String_Length_Bit_Size         = 0x6f,
	String_Length_Byte_Size        = 0x70,
	Rank                           = 0x71,
	Str_Offsets_Base               = 0x72,
	Addr_Base                      = 0x73,
	Rnglists_Base                  = 0x74,
	Dwo_Name                       = 0x76,
	Reference                      = 0x77,
	Rvalue_Reference               = 0x78,
	Macros                         = 0x79,
	Call_All_Calls                 = 0x7a,
	Call_All_Source_Calls          = 0x7b,
	Call_All_Tail_Calls            = 0x7c,
	Call_Return_Pc                 = 0x7d,
	Call_Value                     = 0x7e,
	Call_Origin                    = 0x7f,
	Call_Parameter                 = 0x80,
	Call_Pc                        = 0x81,
	Call_Tail_Call                 = 0x82,
	Call_Target                    = 0x83,
	Call_Target_Clobbered          = 0x84,
	Call_Data_Location             = 0x85,
	Call_Data_Value                = 0x86,
	Noreturn                       = 0x87,
	Alignment                      = 0x88,
	Export_Symbols                 = 0x89,
	Deleted                        = 0x8a,
	Defaulted                      = 0x8b,
	Loclists_Base                  = 0x8c,
	Lo_User                        = 0x2000, // Implementation-defined range start.
	Hi_User                        = 0x3fff, // Implementation-defined range end.

	// SGI/MIPS extensions.
	MIPS_Fde                       = 0x2001,
	MIPS_Loop_Begin                = 0x2002,
	MIPS_Tail_Loop_Begin           = 0x2003,
	MIPS_Epilog_Begin              = 0x2004,
	MIPS_Loop_Unroll_Factor        = 0x2005,
	MIPS_Software_Pipeline_Depth   = 0x2006,
	MIPS_Linkage_Name              = 0x2007,
	MIPS_Stride                    = 0x2008,
	MIPS_Abstract_Name             = 0x2009,
	MIPS_Clone_Origin              = 0x200a,
	MIPS_Has_Inlines               = 0x200b,

	// HP extensions.
	HP_Block_Index                 = 0x2000,
	HP_Unmodifiable                = 0x2001, // Same as AT.MIPS_Fde.
	HP_Prologue                    = 0x2005, // Same as AT.MIPS_Loop_Unroll.
	HP_Epilogue                    = 0x2008, // Same as AT.MIPS_Stride.
	HP_Actuals_Stmt_List           = 0x2010,
	HP_Proc_Per_Section            = 0x2011,
	HP_Raw_Data_Ptr                = 0x2012,
	HP_Pass_By_Reference           = 0x2013,
	HP_Opt_Level                   = 0x2014,
	HP_Prof_Version_Id             = 0x2015,
	HP_Opt_Flags                   = 0x2016,
	HP_Cold_Region_Low_Pc          = 0x2017,
	HP_Cold_Region_High_Pc         = 0x2018,
	HP_All_Variables_Modifiable    = 0x2019,
	HP_Linkage_Name                = 0x201a,
	HP_Prof_Flags                  = 0x201b, // In comp unit of procs_Info for -g.
	HP_Unit_Name                   = 0x201f,
	HP_Unit_Size                   = 0x2020,
	HP_Widened_Byte_Size           = 0x2021,
	HP_Definition_Points           = 0x2022,
	HP_Default_Location            = 0x2023,
	HP_Is_Result_Param             = 0x2029,

	// GNU extensions.
	Sf_Names                       = 0x2101,
	Src_Info                       = 0x2102,
	Mac_Info                       = 0x2103,
	Src_Coords                     = 0x2104,
	Body_Begin                     = 0x2105,
	Body_End                       = 0x2106,
	GNU_Vector                     = 0x2107,
	// Thread-safety annotations.
	// See http://gcc.gnu.org/wiki/ThreadSafetyAnnotation .
	GNU_Guarded_By                 = 0x2108,
	GNU_Pt_Guarded_By              = 0x2109,
	GNU_Guarded                    = 0x210a,
	GNU_Pt_Guarded                 = 0x210b,
	GNU_Locks_Excluded             = 0x210c,
	GNU_Exclusive_Locks_Required   = 0x210d,
	GNU_Shared_Locks_Required      = 0x210e,
	// One-definition rule violation detection.
	// See http://gcc.gnu.org/wiki/DwarfSeparateTypeInfo .
	GNU_Odr_Signature              = 0x210f,
	// Template template argument name.
	// See http://gcc.gnu.org/wiki/TemplateParmsDwarf .
	GNU_Template_Name              = 0x2110,
	// The GNU call site extension.
	// See http://www.dwarfstd.org/ShowIssue.php?issue=100909.2&type=open .
	GNU_Call_Site_Value            = 0x2111,
	GNU_Call_Site_Data_Value       = 0x2112,
	GNU_Call_Site_Target           = 0x2113,
	GNU_Call_Site_Target_Clobbered = 0x2114,
	GNU_Tail_Call                  = 0x2115,
	GNU_All_Tail_Call_Sites        = 0x2116,
	GNU_All_Call_Sites             = 0x2117,
	GNU_All_Source_Call_Sites      = 0x2118,
	// Section offset into .debug_Macro section.
	GNU_Macros                     = 0x2119,
	// Extensions for Fission.  See http://gcc.gnu.org/wiki/DebugFission.
	GNU_Dwo_Name                   = 0x2130,
	GNU_Dwo_Id                     = 0x2131,
	GNU_Ranges_Base                = 0x2132,
	GNU_Addr_Base                  = 0x2133,
	GNU_Pubnames                   = 0x2134,
	GNU_Pubtypes                   = 0x2135,
	// VMS extensions.
	VMS_Rtnbeg_Pd_Address          = 0x2201,
	// GNAT extensions.
	// GNAT descriptive type.
	// See http://gcc.gnu.org/wiki/DW_AT_GNAT_Descriptive_Type .
	Use_GNAT_Descriptive_Type      = 0x2301,
	GNAT_Descriptive_Type          = 0x2302,

	// Zig extensions.
	ZIG_Parent                     = 0x2ccd,
	ZIG_Padding                    = 0x2cce,
	ZIG_Relative_Decl              = 0x2cd0,
	ZIG_Decl_Line_Relative         = 0x2cd1,
	ZIG_Sentinel                   = 0x2ce2,

	// UPC extension.
	Upc_Threads_Scaled             = 0x3210,
	// PGI (STMicroelectronics) extensions.
	PGI_Lbase                      = 0x3a00,
	PGI_Soffset                    = 0x3a01,
	PGI_Lstride                    = 0x3a02,
}
